---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  description: Clean workspace safely
  workspaces:
    - name: source

  steps:
    - name: remove
      image: registry.access.redhat.com/ubi8/ubi-minimal
      workingDir: $(workspaces.source.path)

      securityContext:
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault

      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)

      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Cleaning workspace: ${WORKSPACE_SOURCE_PATH}"

        if [ -d "${WORKSPACE_SOURCE_PATH}" ]; then
          rm -rf "${WORKSPACE_SOURCE_PATH:?}/"*
          rm -rf "${WORKSPACE_SOURCE_PATH}/."[!.]?*
          rm -rf "${WORKSPACE_SOURCE_PATH}/"..?*
        else
          echo "Nothing to clean."
        fi


---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source

  params:
    - name: args
      type: string
      default: "-v"

  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)

      securityContext:
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault

      script: |
        #!/bin/bash
        set -e
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
        nosetests $(params.args)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  workspaces:
    - name: output
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: "main"

  steps:
    - name: clone
      image: registry.redhat.io/openshift/tools:latest
      workingDir: $(workspaces.output.path)
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
      script: |
        #!/usr/bin/env sh
        set -eux

        if [ -d "$(workspaces.output.path)/.git" ]; then
          rm -rf $(workspaces.output.path)/.git
        fi

        git clone $(params.url) .
        git checkout $(params.revision)